using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Radzen;
using CDAApp.Client;
using Microsoft.AspNetCore.Components.Authorization;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.Services.AddScoped<DialogService>();
builder.Services.AddScoped<NotificationService>();
builder.Services.AddScoped<TooltipService>();
builder.Services.AddScoped<ContextMenuService>();
builder.Services.AddTransient(sp => new HttpClient{BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)});
builder.Services.AddScoped<CDAApp.Client.CdaDBService>();
builder.Services.AddAuthorizationCore();
builder.Services.AddHttpClient("CDAApp.Server", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress));
builder.Services.AddTransient(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("CDAApp.Server"));
builder.Services.AddScoped<CDAApp.Client.SecurityService>();
builder.Services.AddScoped<AuthenticationStateProvider, CDAApp.Client.ApplicationAuthenticationStateProvider>();
var host = builder.Build();
await host.RunAsync();